trigger:
- main

pool:
  name: "ubuntu-latest"

steps:
- script: |
    echo "Copying files from Azure DevOps to Azure Storage Account"

    # Install Azure CLI
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    # Login to Azure
    az login --service-principal -u $APPID -p $APPSECRET --tenant $TENANTID

    # List of repositories
    repos=("DEVOPS_TRAINING")

    for repo in "${repos[@]}"
    do
        # Clone the repository
        #git clone https://$(PATTOKEN)@dev.azure.com/goremutual/GorePlatformEngineering/_git/$repo
        git clone https://$(PATTOKEN)github.com/cloudforgedacademy/storage-account-staticweb.git/$repo

        # Remove unwanted files and folders BEFORE uploading
        find $repo -type f -name "*.yaml" -exec rm -f {} \;
        rm -rf $repo/.git
        rm -rf $repo/s

        # Upload the repository folder recursively to Azure Storage Account
        az storage blob upload-batch --account-name $STORAGEACC --account-key $STORAGEACCKEY \
          --destination $CONTAINER --source $repo --overwrite

        # Remove the local repository folder to save space
        rm -rf $repo
    done

  env:
    APPSECRET: $(AppSecret)
    PATTOKEN: $(PatToken)
    APPID: $(AppId)
    TENANTID: $(TenantId)
    STORAGEACC: $(StorageAcc)
    STORAGEACCKEY: $(StorageAccKey)
    CONTAINER: $(Container)

  displayName: 'Adding Azure DevOps Repositories to Azure Storage Account'